version: "3.9"
services:
  api:
    build: ./backend
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app
    command: ["poetry", "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0"]
  frontend:
    image: node:22
    working_dir: /web
    volumes:
     - ./frontend:/web
    command: ["npm", "run", "dev", "--", "--host"]
    ports: ["5173:5173"]
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tick
      POSTGRES_PASSWORD: dash
      POSTGRES_DB: ticks
    ports: ["5432:5432"]
