version: "3.9"
services:
  api:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://tick:dash@db:5432/ticks
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app
    command: ["poetry", "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0"]
  frontend:
    image: node:20-bullseye
    working_dir: /web
    volumes:
     - ./frontend:/web
    command: ["sh", "-c", "npm ci && npm run dev -- --host"]
    ports: ["5173:5173"]
    environment:
    - CHOKIDAR_USEPOLLING=true
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tick
      POSTGRES_PASSWORD: dash
      POSTGRES_DB: ticks
    ports: ["5432:5432"]
